baseURL = 'https://dhmnr.sh/'
languageCode = 'en-us'
title = 'dhmnr.sh'
theme = 'archie'

[params]
  mode = "toggle" # color mode: light, dark, or auto
  useCDN = false
  subtitle = "everything."
  mathjax = false # enable MathJax support
  katex = true # enable KaTeX support
  customCSS = ["css/jetbrains-mono.css", "css/speedrun.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main menu items
[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "about"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "tags"
  url = "/tags"
  weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'